Summary: mkinitramfs
Name: mkinitramfs
Version: 0.4.1
Release: 1
Group: System Environment/Base
License: GPLv2
Distribution: LightCube OS
Vendor: LightCube Solutions
Buildarch: noarch
URL: http://dev.lightcube.us/projects/lightcubeos
Source0: http://dev.lightcube.us/sources/%{name}/%{name}-%{version}.tar.bz2

Requires: base-layout
Requires: glibc
Requires: bash
Requires: gzip
Requires: cpio
Requires: mdadm
Requires: ncurses
Requires: readline
Requires: psmisc
Requires: module-init-tools
Requires: util-linux-ng
BuildRequires: digest(sha1:%{SOURCE0}) = 104bd13f498c59c67389069426355715b62f55f4

%description
A simple script to generate an initramfs file for a specified kernel.

%prep
%setup -q

%build

%install
make DESTDIR=%{buildroot} install

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root)
/usr/bin/mkinitramfs
/usr/share/mkinitramfs

%changelog
* Sat Sep 17 2010 Jeremy Huntwork <jhuntwork@lightcubesolutions.com> - 0.4.1-1
- Upgrade to 0.4.1
- Fixes switch_root usage, restructure to avoid repeating code.
- Make /dev a tmpfs file system, add mknod to the initramfs

* Fri Sep 17 2010 Jeremy Huntwork <jhuntwork@lightcubesolutions.com> - 0.4-1
- Upgrade to 0.4
- Add virtio drivers to initramfs
- Use switch_root instead of manual commands

* Wed Sep 15 2010 Jeremy Huntwork <jhuntwork@lightcubesolutions.com> - 0.3-1
- Upgrade to 0.3
- Name initramfs file such that grub-mkconfig autodetects it
- Add support for UUID labels as generated by grub-mkconfig

* Mon Sep 13 2010 Jeremy Huntwork <jhuntwork@lightcubesolutions.com> - 0.2-1
- Upgrade to 0.2 - add support for software raid

* Tue Aug 10 2010 Jeremy Huntwork <jhuntwork@lightcubesolutions.com> - 0.1-1
- Initial version
