#!/bin/sh -e

usage="
Usage: $0 URL sha256sum

Download a given URL, saving the content as a file named like the basename
element of the URL in the current directory, and verify integrity using a
given sha256 checksum.

If a local file of the same name exists and the checksum matches, downloading
is skipped.

WARNING: If a local file of the same name exists and the checksum does not
match, the remote content is downloaded, OVERWRITING the local file, and the
checksum is verified.
"

error() {
    printf '%s\n' "$*"
    exit 1
}

[ $# -eq 2 ] || error "$usage"

if ! printf '' | sha256sum - >/dev/null 2>&1 ; then
    if printf '' | shasum -a 256 - >/dev/null 2>&1 ; then
        alias sha256sum='shasum -a 256'
    else
        error "Cannot determine a sha256sum binary to use."
    fi
fi

url=$1
sha=$2
filename=${1##*/}

verify() {
    printf '%s  %s' "$sha" "$filename" | sha256sum -c -
}

if [ ! -f "$filename" ] || ! verify ; then
    curl -LO "$url"
    verify
fi
