#!/bin/bash -e
if [ ! -f PKGBUILD ]; then
    printf '%s does not look like a package directory\n' "$(pwd)"
    exit 1
fi

set -o pipefail
shas=$(makepkg -g | cut -d\' -f2)
# shellcheck disable=SC2086
perl -0777 -i -pe "s/sha256sums=([^)]*)/sha256sums=(\\n$(printf '    %s\n' $shas)\\n/" \
    PKGBUILD
